version: 2

updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "@probably-not"
    open-pull-requests-limit: 10
  - package-ecosystem: "mix"
    directory: "/demo"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "@probably-not"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "@probably-not"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "@probably-not"
